### ISSUE TITLE
Enhancement: Document custom characters

### ISSUE THREAD

**Issue by EliteMasterEric** [MasterEric/Kade-Engine#21]
https://github.com/EnigmaEngine/EnigmaEngine/wiki/Custom-Characters

**Comment by isakube** [comment]
Why use the wiki when you can just set up a GitHub Pages environment? It can have some drip, and others can actually PR to a Pages environment.

**Comment by EliteMasterEric** [comment]
Moved to EnigmaEngine/EnigmaEngine.github.io#2
