### ISSUE TITLE
Enhancement: Document 9-key

### ISSUE THREAD

**Issue by EliteMasterEric** [MasterEric/Kade-Engine#22]
no docs for it

**Comment by isakube** [comment]
Are we gonna put 9K support in New Enigma Engine `stable / develop` as well, then?

**Comment by EliteMasterEric** [comment]
9-key support is in develop right now, but develop isn't building rn because I'm still working on revamping the Story Menu to support custom weeks. It's slow but important groundwork.

I haven't tested recently to make sure everything's peachy right now, and charting support isn't fully implemented, but once develop is functional the charter should display 18 columns, 9 for each side. Adding the attribute `strumlineSize` to `song` will allow you to define how many strumlines display for each player. Any number from 1 to 9 is supported.

**Comment by isakube** [comment]
> Any number from 1 to 9 is supported.

Rhythm Doctor time 8)

**Comment by EliteMasterEric** [comment]
Moved to EnigmaEngine/EnigmaEngine.github.io#1
