### ISSUE TITLE
Enhancement: Custom Difficulties

### ISSUE THREAD

**Issue by EliteMasterEric** [MasterEric/Kade-Engine#23]
We should allow mods to include songs with Noob/Expert/Insane difficulties, for example, without modifying the engine code.

Accidentally posted this to KadeDev/Kade-Engine#2398

**Comment by isakube** [comment]
pasted from KE lol:

My idea is that when we check the charts in freeplay menu to see if the difficulties exist, we check for other charts besides Easy, Normal, and Hard. we take those charts' difficulty suffixes and add them to the available difficulties for that chart. Freeplay-only implementation, but it's a start. Obv more complicated than this explanation though

**Comment by EliteMasterEric** [comment]
I've got an implementation in the works that reads the list of possible difficulties from a data file like how the list of Freeplay songs is. It then checks each song for a chart of that difficulty. Ive implemented it for Story mode too but it's all buggy rn

**Comment by EliteMasterEric** [comment]
This is implemented
