### ISSUE TITLE
0.2.0 - LEFT and DOWN notes are switched

### ISSUE THREAD

**Issue by aladairmaxwell** [MasterEric/Kade-Engine#26]
As title says. LEFT arrow works as DOWN arrow and vice versa. The game isn't playable. My controls set by default. 

Also pixel notes screwed up.

![image](https://user-images.githubusercontent.com/69295711/135706648-d5cfcb0f-6e4f-446a-9982-a15ff8e0f307.png)

[1633156745.905.log](https://github.com/EnigmaEngine/EnigmaEngine/files/7270991/1633156745.905.log)

**Comment by EliteMasterEric** [comment]
To help keep this organized I split this into two issues, #27 and #28.
