### ISSUE TITLE
[BUG] Strumlines not varying based on note style

### ISSUE THREAD

**Issue by EliteMasterEric** [MasterEric/Kade-Engine#28]
It appears that even on Week 6 (which uses the `pixel` notestyle for all songs), the default notestyle is used for the strumlines.

**Comment by EliteMasterEric** [comment]
![image](https://user-images.githubusercontent.com/4635334/135744353-0d0f47d8-15c3-4df3-a624-63e8a7b33515.png)

**Comment by aladairmaxwell** [comment]
Also look how blurry notes are, that's not good

**Comment by isakube** [comment]
> Also look how blurry notes are, that's not good

antialiasing off. br

**Comment by EliteMasterEric** [comment]
Pretty sure it's fixed

**Comment by isakube** [comment]
lets go
