### ISSUE TITLE
Enhancement: Custom Weeks

### ISSUE THREAD

**Issue by EliteMasterEric** [MasterEric/Kade-Engine#3]
Make story weeks data driven so that custom weeks can be added to the story menu.

**Comment by isakube** [comment]
The week list in StoryMenuState is a function, is it not? If we tweak it to take an hscript result (`@:hscript`), would that work?

Then we just do that for the default weeklocks and story characters.

**Comment by EliteMasterEric** [comment]
My plan was to make a JSON file which can be modified by merging using ModCore.

**Comment by EliteMasterEric** [comment]
Done in version 0.3.
