### ISSUE TITLE
`develop` Bug Report: FPS caps at 2 when transitioning to another state

### ISSUE THREAD

**Issue by isakube** [MasterEric/Kade-Engine#63]
### If you are playing a downloaded version of the game, what operating system are you using?
macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
Latest `develop` commit as of `9/10/21 7:30PM US West Coast`

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
exist

## Please describe your issue. Provide extensive detail and images if possible.
When you transition between states, the FPS caps at 2 for seemingly no reason. The only way to fix this is by unfocusing and refocusing the window.

**Comment by EliteMasterEric** [comment]
> `9/10/21 7:30PM US West Coast`

You sure? That's really old.

I need to update the bug report template to include this, but please upload a log file from the game folder if you can. It gives me a lot of useful information (including the exact git commit hash the game was built from).

**Comment by isakube** [comment]
> > `9/10/21 7:30PM US West Coast`
> 
> You sure? That's really old.
> 
> I need to update the bug report template to include this, but please upload a log file from the game folder if you can. It gives me a lot of useful information (including the exact git commit hash the game was built from).

that's when i first compiled the game so \\_[.\_.]\_/

**Comment by EliteMasterEric** [comment]
Latest develop commit is 2 days ago please check that

**Comment by isakube** [comment]
fixed.
